### ISSUE TITLE
请不要用"白皙母狗"这种字眼形容我们的女神！！

### ISSUE THREAD

**Issue by Robertxzx** [miyatv/myhome#3]
https://www.my0sz4b4eu9i3bhi8d439plktds.xyz:59980/index.php/vod/play/id/129090/sid/1/nid/1.html
[歐美]:狂顶白皙母狗的圆润大屁股
请你把”狂顶白皙母狗“换成“白皙美女”，因为你这样做会助长男权社会对女性不尊重的风气！！这个AV演员都是我们观众的女神，谢谢！！！

**Comment by Robertxzx** [comment]
既然本来就是复制盗版别人的电影了，请不要乱用词汇来表述我们漂亮的AV演员！！谢谢

**Comment by a946-63** [comment]
看不了了，怎么回事

**Comment by 8280-max** [comment]
视频无法加载
